config/routes.rb
Rails.application.routes.draw do
  root to: 'patterns#index'
  resources :patterns

end

app/models/pattern.rb
require 'grid_generator'

class Pattern < ActiveRecord::Base
  validates_presence_of :minor_x
  validates_presence_of :minor_y
  validates_presence_of :major_x
  validates_presence_of :major_y
  before_save :create_grid

  private

  def create_grid
    generator = GridGenerator.new(self.minor_x, self.major_x, self.minor_y, self.major_y)
    self.grid = generator.generate
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: [:show, :edit, :update, :destroy]

  # GET /patterns
  # GET /patterns.json
  def index
    @pattern = Pattern.new
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  def create
    @pattern = Pattern.new(pattern_params)

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: 'Pattern was successfully created.' }
        format.json { render :show, status: :created, location: @pattern }
      else
        format.html { render :new }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { render :show, status: :ok, location: @pattern }
      else
        format.html { render :edit }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url, notice: 'Pattern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      params.require(:pattern).permit(:minor_x, :major_x, :minor_y, :major_y)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grid Generator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patterns/_form.html.erb
<%= form_for(@pattern) do |f| %>
  <% if @pattern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pattern.errors.count, "error") %> prohibited this pattern from being saved:</h2>

      <ul>
      <% @pattern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :minor_x %><br>
    <%= f.number_field :minor_x %>
  </div>
  <div class="field">
    <%= f.label :major_x %><br>
    <%= f.number_field :major_x %>
  </div>
  <div class="field">
    <%= f.label :minor_y %><br>
    <%= f.number_field :minor_y %>
  </div>
  <div class="field">
    <%= f.label :major_y %><br>
    <%= f.number_field :major_y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patterns/edit.html.erb
<h1>Editing pattern</h1>

<%= render 'form' %>

<%= link_to 'Show', @pattern %> |
<%= link_to 'Back', patterns_path %>

app/views/patterns/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/stylish-portfolio.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <a href="#top">Navigation</a>
            </li>
            <li>
                <a href="https://github.com/austinhansen/code_test/blob/master/app/services/grid_generator.rb">Source</a>
            </li>
            <li>
                <a href="mailto:austintatious@gmail.com">Contact</a>
            </li>
        </ul>
    </nav>

    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>Have you ever wondered?</h1>
            <h3>What it would be like to generate a grid of X's and O's?</h3>
            <h5>(Based off of 4 input values?)</h5>
            <br>
            <%= simple_form_for @pattern, html: {class: 'form-inline' } do |f| %>
              <%= f.input :minor_x, label: 'Minor X' %>
              <%= f.input :major_x, label: 'Major X' %>
              <%= f.input :minor_y, label: 'Minor Y' %>
              <%= f.input :major_y, label: 'Major Y' %>
              <%= f.button :submit, class: 'btn btn-dark btn-lg', value: 'Wonder no more!' %>
            <% end %>
            <!-- <a href="#about" class="btn btn-dark btn-lg">Wonder no more!</a> -->
        </div>
    </header>


    <!-- jQuery Version 1.11.0 -->
    <script src="/assets/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/assets/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    </script>

</body>

</html>

app/views/patterns/new.html.erb
<h1>New pattern</h1>

<%= render 'form' %>

<%= link_to 'Back', patterns_path %>

app/views/patterns/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/stylish-portfolio.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans+Mono' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

  <!-- Header -->
  <header id="top" class="header">
      <div class="text-vertical-center">
        <p>
          <% @pattern.grid.each do |x| %>
            <%= x %>
            <br>
          <% end %>
        </p>
      </div>
  </header>
</body>